### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by JulianEgbert** [hpi-swt2/compass-portal-blue#140]
When logging in with OpenID I get an error and the page won't load:
![image](https://user-images.githubusercontent.com/57799997/148441177-2ca8d95c-bbf6-4c43-be3e-009e4b60721e.png)

**Comment by laugengebaeck** [comment]
This bug was probably introduced in #88. Maybe someone from @hpi-swt2/rh21 knows more about this?

**Comment by Olliwehr** [comment]
In my opinion #88 isn't really causing that. Maybe you had an old state for user data in your local DB before the prior user model (with username & email and e.g. a profile picture) was split back into a _User_ and a _Person_ model (with #85).
Unfortunately, running the migrations on the DB doesn't really fix the issue. Locally i dropped my old Databases and created fresh ones and now it is working, but i feel like that is not really a solution.

Mabye @bewee could enlighten as a bit more about the separation between user and person data?

**Comment by JulianEgbert** [comment]
I also don't have any search results when i try to search for example myself. I'm not sure on how to get the database "filled"

**Comment by bewee** [comment]
We had to separate Person and User into separate classes, because we may want to find some important persons like Hasso in the search although they probably won't ever log into our app.
Whenever you login with your account, a new person will be automatically added for you. However, the migration did not apply this to existing datasets. Thus, you have a user with no associated person, which is prohibited. 
We suggest simply dropping and recreating the database.
```
rails db:drop
rails db:migrate
```
> I also don't have any search results when i try to search for example myself. I'm not sure on how to get the database "filled"

Not sure whether this works, but we often had luck solving problems by clearing the webpack cache
```
./bin/webpack --cache
```
Does this help?
